// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TEST.Models;

public partial class Member
{
    public Guid ID { get; set; }

	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public int Pid { get; set; }

	public string NAME { get; set; }

	public string INFO { get; set; }

	public DateTime CreateDt { get; set; }
}