// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TEST.Models;

public partial class NetTestContext : DbContext
{
    public NetTestContext(DbContextOptions<NetTestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Member> Member { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Member>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedNever();
            entity.Property(e => e.CreateDt).HasColumnType("datetime");
            entity.Property(e => e.INFO).IsRequired();
            entity.Property(e => e.NAME)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}